#!/usr/bin/env ruby

if ARGV[0] == "backup"
  backup
elsif ARGV.count == 2 and ARGV[0][0..5] == "camera" and ARGV[1][0..5] == "camera"
  change_camera_position(ARGV[0],ARGV[1])
else
  puts "\nUSAGE\n"
  puts "$ chpos from to"
  puts "\nEXAMPLE"
  puts "To move camera4 into position one you would do;"
  puts "$ chpos camera4 camera1\n\n"
end
